### ISSUE TITLE
Not able to connect to the app

### ISSUE THREAD

**Issue by Madhu-gh** [Lightning-Universe/Training-Studio_app#227]
## 🐛 Bug

I'm not able to connect to the Trainer studio App because of the error. None of the lightning command works. It is kept showing this error below
```
  File "/Users/madhumathiyalagan/lightning-hpo/lightning_hpo/framework/agnostic.py", line 6, in <module>
    from typing import Any, Dict, Optional, TypedDict
ImportError: cannot import name 'TypedDict' from 'typing' (/Users/madhumathiyalagan/miniconda3/envs/prod-12265/lib/python3.7/typing.py)
```

### To Reproduce
1. Open Terminal 
2. make_prod
3. Do ---> step 1 [here](https://lightning-ai.github.io/lightning-hpo/installation.html)
```
git clone https://github.com/Lightning-AI/lightning-hpo && cd lightning-hpo

pip install -e . -r requirements.txt --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
```
4. Do ---> Step 3 [here](https://lightning-ai.github.io/lightning-hpo/installation.html)
`PACKAGE_LIGHTNING=1 python -m lightning run app app.py --cloud`
5. Click ---> OpenApp 
6. Connect to app  ---> `lightning connect 01gkmref244yjm4zv3gqs860ef --yes`

Then I get the below error

![image](https://user-images.githubusercontent.com/118762348/206037229-ec125c39-2181-4ffb-8976-18c86ebbc302.png)

### Environment

- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

**Comment by lantiga** [comment]
This is because you are using Python 3.7.
In the Installation section we explicitly state we require Python 3.8+
